name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Velkommen! Hvis du har noen spørsmål, send meg en melding på https://twitter.com/hallis1221 eller mail; halvorviv@gmail.com"
        pr-message: "Velkommen! Hvis du har noen spørsmål, send meg en melding på https://twitter.com/hallis1221 eller mail; halvorviv@gmail.com"
